### ISSUE TITLE
Use alternative enable/disable Macro

### ISSUE THREAD

**Issue by mikeantonelli** [MattesGroeger/MGBenchmark#13]
Currently, the enabling/disabling of benchmarking is done via the [presence of the DEBUG macro](https://github.com/MattesGroeger/MGBenchmark/blob/master/MGBenchmark/MGBenchmark.h#L27). In my usage of this tool, I've wanted to build for Release with benchmarking enabled.

Would you be open to using a different flag?

```
#ifdef MGBENCHMARK
...
```

**Comment by MattesGroeger** [comment]
Hi @mikeantonelli, sure thing. Would there be an easy way to map DEBUG to MGBENCHMARK then?

**Comment by mikeantonelli** [comment]
@MattesGroeger You could default the value when DEBUG is set:

```
ifdef DEBUG
  MGBENCHMARK = 1
endif
```

This would allow for existing functionality to work (ie: in debug benchmarking is enabled), but also allows a consumer to explicitly set MGBENCHMARK=1 in additional build configurations.

**Comment by MattesGroeger** [comment]
Great solution :+1:
